apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hdr-empire.fullname" . }}
  labels:
    {{- include "hdr-empire.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
