apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hdr-empire.fullname" . }}
  labels:
    {{- include "hdr-empire.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.secrets.redis.password | quote }}
  jwt-secret: {{ .Values.secrets.jwt.secret | quote }}
  encryption-key: {{ .Values.secrets.encryption.key | quote }}
